"use client"

import { useEffect, useState } from "react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Download } from "lucide-react"
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, ReferenceArea } from 'recharts'
import jsPDF from "jspdf"
import html2canvas from "html2canvas"

export default function TrendsPage() {
  const [trends, setTrends] = useState<any[]>([])
  const [loading, setLoading] = useState(true)
  const [months, setMonths] = useState(6)
  const [generatingPdf, setGeneratingPdf] = useState(false)

  useEffect(() => {
    async function fetchTrends() {
      setLoading(true)
      const res = await fetch(`/api/metrics/trends?months=${months}`)
      if (res.ok) {
        const data = await res.json()
        setTrends(data)
      }
      setLoading(false)
    }
    fetchTrends()
  }, [months])

  const formatDate = (dateStr: string) => {
    return new Date(dateStr).toLocaleDateString(undefined, { month: 'short', year: 'numeric' })
  }

  const generatePDF = async () => {
    setGeneratingPdf(true)
    try {
      // 1. Fetch AI Summary
      const res = await fetch('/api/generate-summary', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ metrics: trends })
      })
      const data = await res.json()
      const aiSummary = data.summary || "AI Summary unavailable."

      // 2. Capture charts as image
      const chartsContainer = document.getElementById("charts-container")
      let chartImgData = null
      if (chartsContainer) {
        // Temporarily adjust styles for better screenshot
        const originalBg = chartsContainer.style.background
        chartsContainer.style.background = 'white'
        const canvas = await html2canvas(chartsContainer, { scale: 2 })
        chartImgData = canvas.toDataURL('image/png')
        chartsContainer.style.background = originalBg
      }

      // 3. Assemble PDF
      const doc = new jsPDF()
      
      // Header
      doc.setFontSize(22)
      doc.setTextColor(13, 148, 136) // Teal color for BioBytes
      doc.text("BioBytes e-health tracker", 105, 20, { align: "center" })
      
      doc.setFontSize(16)
      doc.setTextColor(0, 0, 0)
      doc.text("AI-Powered Health Trend Report", 105, 30, { align: "center" })
      
      doc.setFontSize(10)
      doc.text(`Generated: ${new Date().toLocaleDateString()}`, 105, 38, { align: "center" })
      
      // AI Summary Section
      doc.setFontSize(14)
      doc.setFont("helvetica", "bold")
      doc.text("AI Doctor Summary & Advice", 15, 50)
      
      doc.setFontSize(10)
      doc.setFont("helvetica", "normal")
      const splitSummary = doc.splitTextToSize(aiSummary, 180)
      doc.text(splitSummary, 15, 58)
      
      let currentY = 60 + (splitSummary.length * 5)
      
      // Charts Section
      if (chartImgData) {
        if (currentY > 200) {
          doc.addPage()
          currentY = 20
        } else {
          currentY += 10
        }
        
        doc.setFontSize(14)
        doc.setFont("helvetica", "bold")
        doc.text("Historical Data Comparison", 15, currentY)
        
        // Add image (x, y, width, height)
        doc.addImage(chartImgData, 'PNG', 15, currentY + 5, 180, 100)
        currentY += 115
      }
      
      // Footer Disclaimer
      doc.setFontSize(8)
      doc.setTextColor(150, 150, 150)
      doc.text(
        "Generated by AI and AI can make mistakes. This is for informational purposes and does not replace professional medical advice.", 
        105, 285, { align: "center" }
      )
      
      // Save PDF
      doc.save("BioBytes_Trend_Report.pdf")
      
    } catch (err) {
      console.error("PDF generation failed:", err)
      alert("Failed to generate PDF. Please try again.")
    } finally {
      setGeneratingPdf(false)
    }
  }

  return (
    <div className="space-y-6 max-w-5xl mx-auto">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Health Trends</h1>
          <p className="text-muted-foreground">Visualize your biomarker changes over time.</p>
        </div>
        <div className="flex items-center gap-2">
          <select 
            value={months} 
            onChange={(e) => setMonths(Number(e.target.value))}
            className="flex h-10 w-[180px] rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2"
            disabled={generatingPdf}
          >
            <option value={3}>Last 3 Months</option>
            <option value={6}>Last 6 Months</option>
            <option value={12}>Last 12 Months</option>
          </select>
          
          <Button 
            onClick={generatePDF} 
            disabled={loading || generatingPdf || trends.length === 0}
            className="flex items-center gap-2"
          >
            <Download className="h-4 w-4" />
            {generatingPdf ? "Generating..." : "Download AI Trend Report"}
          </Button>
        </div>
      </div>

      {loading ? (
        <div className="text-center py-20">Loading trends...</div>
      ) : trends.filter(t => t.data && t.data.length > 0).length === 0 ? (
        <div className="text-center py-20 text-muted-foreground">No trend data available for this period.</div>
      ) : (
        <div id="charts-container" className="grid gap-6 p-2">
          {trends.filter(t => t.data && t.data.length > 0).map((trend) => (
            <Card key={trend.code}>
              <CardHeader>
                <CardTitle>{trend.name}</CardTitle>
                <CardDescription>
                  Reference Range: {trend.refMin} - {trend.refMax} {trend.unit}
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="h-[300px] w-full">
                  <ResponsiveContainer width="100%" height="100%">
                    <LineChart
                      data={trend.data}
                      margin={{ top: 20, right: 30, left: 20, bottom: 5 }}
                    >
                      <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e5e7eb" />
                      <XAxis 
                        dataKey="date" 
                        tickFormatter={formatDate}
                        tick={{ fontSize: 12, fill: '#6b7280' }}
                        axisLine={false}
                        tickLine={false}
                      />
                      <YAxis 
                        domain={['auto', 'auto']}
                        tick={{ fontSize: 12, fill: '#6b7280' }}
                        axisLine={false}
                        tickLine={false}
                      />
                      <Tooltip 
                        labelFormatter={(label: any) => formatDate(label as string)}
                        formatter={(value: any) => [`${value} ${trend.unit}`, trend.name]}
                      />
                      {trend.refMin !== null && trend.refMax !== null && (
                        <ReferenceArea 
                          y1={trend.refMin} 
                          y2={trend.refMax} 
                          fill="#10b981" 
                          fillOpacity={0.1} 
                        />
                      )}
                      <Line 
                        type="monotone" 
                        dataKey="value" 
                        stroke="#0d9488" 
                        strokeWidth={3}
                        activeDot={{ r: 8 }}
                      />
                    </LineChart>
                  </ResponsiveContainer>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
  )
}
