"use client"

import { useEffect, useState } from "react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Download, Search, FileX } from "lucide-react"
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, ReferenceArea } from 'recharts'
import jsPDF from "jspdf"
import html2canvas from "html2canvas"
import Link from "next/link"

export function PatientTrendsDashboard({ accessCode }: { accessCode?: string }) {
  const [trends, setTrends] = useState<any[]>([])
  const [loading, setLoading] = useState(true)
  const [months, setMonths] = useState(6)
  const [generatingPdf, setGeneratingPdf] = useState(false)
  const [activeCategory, setActiveCategory] = useState("All")
  const [searchQuery, setSearchQuery] = useState("")

  useEffect(() => {
    async function fetchTrends() {
      setLoading(true)
      const url = accessCode 
        ? `/api/metrics/trends?months=${months}&accessCode=${accessCode}`
        : `/api/metrics/trends?months=${months}`
      const res = await fetch(url)
      if (res.ok) {
        const data = await res.json()
        setTrends(data)
      }
      setLoading(false)
    }
    fetchTrends()
  }, [months, accessCode])

  const formatDate = (dateStr: string) => {
    return new Date(dateStr).toLocaleDateString(undefined, { day: 'numeric', month: 'short', year: 'numeric' })
  }

  // Deduplicate categories for the selector
  const categories = ["All", ...Array.from(new Set(trends.map(t => t.category)))]

  // Filter trends based on category, search query, and presence of data
  const filteredTrends = trends.filter(t => {
    if (t.history.length === 0) return false;
    
    const matchesCategory = activeCategory === "All" || t.category === activeCategory
    const matchesSearch = t.name.toLowerCase().includes(searchQuery.toLowerCase())
    return matchesCategory && matchesSearch
  })

  const generatePDF = async () => {
    setGeneratingPdf(true)
    try {
      const populatedTrends = trends.filter(t => t.history && t.history.length > 0)
      
      const res = await fetch('/api/generate-summary', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ metrics: populatedTrends })
      })
      const data = await res.json()
      const aiSummary = data.summary || "AI Summary unavailable."

      const chartsContainer = document.getElementById("charts-container")
      let chartImgData = null
      if (chartsContainer) {
        const originalBg = chartsContainer.style.background
        chartsContainer.style.background = 'white'
        // Filter out empty state elements for PDF generation to keep it clean
        const emptyStates = chartsContainer.querySelectorAll('.empty-state-chart')
        emptyStates.forEach((el: any) => el.style.display = 'none')
        
        const canvas = await html2canvas(chartsContainer, { scale: 2 })
        chartImgData = canvas.toDataURL('image/png')
        
        emptyStates.forEach((el: any) => el.style.display = 'flex')
        chartsContainer.style.background = originalBg
      }

      const doc = new jsPDF()
      doc.setFontSize(22)
      doc.setTextColor(13, 148, 136)
      doc.text("BioBytes e-health tracker", 105, 20, { align: "center" })
      
      doc.setFontSize(16)
      doc.setTextColor(0, 0, 0)
      doc.text("AI-Powered Health Trend Report", 105, 30, { align: "center" })
      
      doc.setFontSize(10)
      doc.text(`Generated: ${new Date().toLocaleDateString()}`, 105, 38, { align: "center" })
      
      doc.setFontSize(14)
      doc.setFont("helvetica", "bold")
      doc.text("AI Doctor Summary & Advice", 15, 50)
      
      doc.setFontSize(10)
      doc.setFont("helvetica", "normal")
      const splitSummary = doc.splitTextToSize(aiSummary, 180)
      doc.text(splitSummary, 15, 58)
      
      let currentY = 60 + (splitSummary.length * 5)
      
      if (chartImgData) {
        if (currentY > 200) {
          doc.addPage()
          currentY = 20
        } else {
          currentY += 10
        }
        doc.setFontSize(14)
        doc.setFont("helvetica", "bold")
        doc.text("Historical Data Comparison", 15, currentY)
        doc.addImage(chartImgData, 'PNG', 15, currentY + 5, 180, 100)
        currentY += 115
      }
      
      doc.setFontSize(8)
      doc.setTextColor(150, 150, 150)
      doc.text(
        "Generated by AI and AI can make mistakes. This is for informational purposes and does not replace professional medical advice.", 
        105, 285, { align: "center" }
      )
      
      doc.save("BioBytes_Trend_Report.pdf")
      
    } catch (err) {
      console.error("PDF generation failed:", err)
      alert("Failed to generate PDF. Please try again.")
    } finally {
      setGeneratingPdf(false)
    }
  }

  return (
    <div className="space-y-6 max-w-6xl mx-auto pb-10">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Health Trends</h1>
          <p className="text-muted-foreground">Visualize your biomarker changes over time.</p>
        </div>
        <div className="flex items-center gap-2">
          <select 
            value={months} 
            onChange={(e) => setMonths(Number(e.target.value))}
            className="flex h-10 w-[180px] rounded-md border border-input bg-background/50 backdrop-blur-sm px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 shadow-sm"
            disabled={generatingPdf}
          >
            <option value={3}>Last 3 Months</option>
            <option value={6}>Last 6 Months</option>
            <option value={12}>Last 12 Months</option>
          </select>
          
          <Button 
            onClick={generatePDF} 
            disabled={loading || generatingPdf || trends.filter(t => t.history.length > 0).length === 0}
            className="flex items-center gap-2 shadow-sm"
          >
            <Download className="h-4 w-4" />
            {generatingPdf ? "Generating..." : "Download Report"}
          </Button>
        </div>
      </div>

      {/* Interactive Search Bar & Glassmorphism Category Selector */}
      <div className="flex flex-col space-y-4">
        <div className="relative">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-5 w-5 text-muted-foreground" />
          <input 
            type="text" 
            placeholder="Search all 100 tests (e.g., Hemoglobin, SGPT, Calcium)..." 
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full h-12 pl-10 pr-4 rounded-xl border border-input bg-background/50 backdrop-blur-md focus:outline-none focus:ring-2 focus:ring-primary shadow-sm transition-all"
          />
        </div>
        
        <div className="flex flex-wrap gap-2">
          {categories.map(cat => (
            <button
              key={cat}
              onClick={() => setActiveCategory(cat)}
              className={`px-4 py-2 rounded-full text-sm font-medium transition-all shadow-sm backdrop-blur-md border ${
                activeCategory === cat 
                  ? 'bg-primary text-primary-foreground border-primary' 
                  : 'bg-background/60 text-muted-foreground hover:bg-muted/80 border-border'
              }`}
            >
              {cat}
            </button>
          ))}
        </div>
      </div>

      {loading ? (
        <div className="text-center py-20 flex flex-col items-center">
          <div className="w-10 h-10 border-4 border-primary border-t-transparent rounded-full animate-spin mb-4"></div>
          <p className="text-muted-foreground font-medium">Loading your health data...</p>
        </div>
      ) : filteredTrends.length === 0 ? (
        <div className="text-center py-20 text-muted-foreground border-2 border-dashed rounded-xl bg-background/50 backdrop-blur-sm">
          No tests found matching your search.
        </div>
      ) : (
        <div id="charts-container" className="grid gap-6 p-2 md:grid-cols-2">
          {filteredTrends.map((trend) => (
            <Card key={trend.code} className="overflow-hidden bg-background/60 backdrop-blur-xl border-white/20 shadow-lg hover:shadow-xl transition-all duration-300">
              <CardHeader className="bg-gradient-to-r from-primary/5 to-transparent pb-4">
                <div className="flex justify-between items-start">
                  <div>
                    <CardTitle className="text-lg text-primary">{trend.name}</CardTitle>
                    <CardDescription className="font-medium mt-1">
                      {trend.category}
                    </CardDescription>
                  </div>
                  {trend.refMin !== null && trend.refMax !== null && (
                    <div className="text-right">
                      <span className="text-xs font-semibold text-muted-foreground uppercase tracking-wider block">Reference Range</span>
                      <span className="text-sm font-medium text-emerald-600 bg-emerald-50 px-2 py-1 rounded-md border border-emerald-100">
                        {trend.refMin} - {trend.refMax} {trend.unit}
                      </span>
                    </div>
                  )}
                </div>
              </CardHeader>
              
              <CardContent className="p-0">
                {trend.history.length > 0 ? (
                  <div className="h-[280px] w-full p-4 relative">
                    <ResponsiveContainer width="100%" height="100%">
                      <LineChart
                        data={trend.history}
                        margin={{ top: 20, right: 30, left: 10, bottom: 5 }}
                      >
                        <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e5e7eb" />
                        <XAxis 
                          dataKey="id" 
                          tickFormatter={(id) => {
                            const point = trend.history.find((d: any) => d.id === id)
                            return point ? formatDate(point.date) : ''
                          }}
                          tick={{ fontSize: 12, fill: '#6b7280' }}
                          axisLine={false}
                          tickLine={false}
                        />
                        <YAxis 
                          domain={[
                            (dataMin: number) => {
                              if (trend.refMin !== null) return Math.floor(Math.min(dataMin, trend.refMin * 0.9));
                              return Math.floor(dataMin * 0.9);
                            },
                            (dataMax: number) => {
                              if (trend.refMax !== null) return Math.ceil(Math.max(dataMax, trend.refMax * 1.1));
                              return Math.ceil(dataMax * 1.1);
                            }
                          ]}
                          tick={{ fontSize: 12, fill: '#6b7280' }}
                          axisLine={false}
                          tickLine={false}
                          width={40}
                        />
                        <Tooltip 
                          content={({ active, payload }) => {
                            if (active && payload && payload.length) {
                              const data = payload[0].payload
                              const exactDate = new Date(data.date).toLocaleDateString(undefined, { day: 'numeric', month: 'short', year: 'numeric' })
                              return (
                                <div className="bg-background/95 backdrop-blur-md p-3 border border-border/50 rounded-xl shadow-xl text-sm">
                                  <p className="font-bold text-foreground">{exactDate}</p>
                                  <p className="text-muted-foreground text-xs mb-1">{data.labName || "Lab Report"}</p>
                                  <p className="text-primary font-bold text-lg">{`${data.value} ${trend.unit}`}</p>
                                </div>
                              )
                            }
                            return null
                          }}
                        />
                        {trend.refMin !== null && trend.refMax !== null && (
                          <ReferenceArea 
                            y1={trend.refMin} 
                            y2={trend.refMax} 
                            fill="#10b981" 
                            fillOpacity={0.08} 
                          />
                        )}
                        <Line 
                          type="monotone" 
                          dataKey="value" 
                          stroke="hsl(var(--primary))" 
                          strokeWidth={4}
                          activeDot={{ r: 8, fill: "hsl(var(--primary))", stroke: "white", strokeWidth: 2 }}
                          dot={{ r: 4, fill: "hsl(var(--primary))", strokeWidth: 0 }}
                        />
                      </LineChart>
                    </ResponsiveContainer>
                  </div>
                ) : (
                  // BEAUTIFUL EMPTY STATE WITH FADED CHART GRID
                  <div className="empty-state-chart h-[280px] w-full p-4 relative flex items-center justify-center">
                    {/* Faded Background Chart */}
                    <div className="absolute inset-0 p-4 opacity-20 pointer-events-none grayscale">
                      <ResponsiveContainer width="100%" height="100%">
                        <LineChart data={[{ id: 1, value: trend.refMax || 100 }, { id: 2, value: trend.refMin || 0 }]} margin={{ top: 20, right: 30, left: 10, bottom: 5 }}>
                          <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e5e7eb" />
                          <XAxis dataKey="id" tick={false} axisLine={false} tickLine={false} />
                          <YAxis domain={['auto', 'auto']} tick={{ fontSize: 12, fill: '#6b7280' }} axisLine={false} tickLine={false} width={40} />
                          <Line type="monotone" dataKey="value" stroke="#9ca3af" strokeWidth={2} strokeDasharray="5 5" dot={false} />
                        </LineChart>
                      </ResponsiveContainer>
                    </div>
                    
                    {/* Glassmorphism Overlay */}
                    <div className="z-10 flex flex-col items-center justify-center p-6 text-center bg-background/60 backdrop-blur-sm rounded-xl border border-white/20 shadow-sm max-w-[80%]">
                      <div className="h-12 w-12 rounded-full bg-muted/80 flex items-center justify-center mb-3 shadow-inner">
                        <FileX className="h-6 w-6 text-muted-foreground/70" />
                      </div>
                      <h3 className="font-semibold text-foreground/90 mb-1 text-sm">No historical data</h3>
                      <p className="text-xs text-muted-foreground max-w-[200px] mb-4">
                        Upload your next report to track {trend.name}.
                      </p>
                      <Link href="/patient/upload">
                        <Button variant="outline" size="sm" className="h-8 text-xs rounded-full shadow-sm hover:shadow-md transition-all bg-background/50">
                          Upload Report
                        </Button>
                      </Link>
                    </div>
                  </div>
                )}
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
  )
}
